Couvre-feu à 18 h pour les départements du N-E
Delegation-numerique-en-sante/mesconseilscovid pull request #677
Opened 2020-12-30 22:41 UTC by davidbgk

Si la rumeur se confirme :

* https://www.lemonde.fr/planete/article/2020/12/29/un-couvre-feu-des-18-heures-envisage-a-partir-du-2-janvier-dans-certains-territoires_6064769_3244.html
* https://www.leparisien.fr/politique/covid-19-decouvrez-la-carte-des-20-departements-ou-le-couvre-feu-pourrait-etre-avance-a-18-heures-29-12-2020-8416569.php

2021-01-01 19:36 UTC, HelaG commented
Pour l'instant j'ai fait ça : https://github.com/Delegation-numerique-en-sante/mesconseilscovid/commit/4b8c3a94ccd247ccef31e6078e61ddf16a2139c0

Mais il faudrait créer 2 fichiers et conditionner leur affichage au département sélectionné par l'utilisateur.

2021-01-01 19:41 UTC, HelaG commented
En fait je n'avais pas vu le détail de ta PR @davidbgk J'ai "défait" mon commit.

2021-01-02 15:36 UTC, ronnix requested changes

2021-01-02 15:36 UTC, ronnix commented on src/scripts/data/departementsCouvreFeu18H.js
> +}
L’Allier (03), l’Ardèche (07), l’Aube (10), le Haut-Rhin (68) et l’Yonne (89) ne sont pas listé sur https://www.gouvernement.fr/info-coronavirus

2021-01-02 15:41 UTC, ronnix approved these changes

2021-01-02 15:53 UTC, merged